config/routes.rb
Rails.application.routes.draw do
  root to: 'recipes#index'
  resources :recipes, only: :show
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :load_recipes

  def index
    @recipes = @recipes_services.find_all
    flash[:notice] = "Total #{@recipes.count} Recipes found!"
  end

  def show
    recipe = @recipes_services.find_by_id
    if recipe
      call_decorator(recipe)
      
      flash[:notice] = 'Recipe is successfully fetched'
    else
      flash[:error]  = 'No Recipe Found!'
    end
  end

  private

  def recipes_params
  	params.permit(:id)
  end

  def load_recipes
  	@recipes_services = RecipesServices::LoadRecipes.new(recipes_params)
  end

  def call_decorator(recipe)
    @recipe = RecipeDecorator.new(recipe)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(level)
		case level
			when :notice  then "alert alert-info"
			when :success then "alert alert-success"
			when :error   then "alert alert-error"
			when :alert   then "alert alert-error"
		end
	end

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarleySpoon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/header' %>
    <%= render partial: 'shared/flash'  %>
    
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/recipes/_recipe.html.erb
<li class="list-group-item d-flex justify-content-between align-items-center">
	<%= link_to recipe.title, recipe_url(recipe.id), target: "_blank" %>
  <div class="image-parent">
    <%= image_tag recipe.photo.url(width: 480, height: 320), class: 'img-responsive' %>
  </div>
</li>

app/views/recipes/index.html.erb
<div class="row justify-content-md-center">
  <div class="col-12 col-sm-10 col-lg-25">
    <ul class="list-group">
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <h3 class="text-muted">List Recipes with Images</h3>
      </li>
      <%= render partial: 'recipe', collection: @recipes, as: :recipe %>
    </ul>
  </div>
</div>

app/views/recipes/show.html.erb
<% if @recipe %>
  <h1 class="my-4">
    <small><%= @recipe.title %></small>
  </h1>
  <div class="row">
    <div class="col-md-8">
      <%= image_tag @recipe.image, class: 'img-fluid' %>
    </div>
    <div class="col-md-4">
      <h3 class="my-3">Recipe Description</h3>
      <p><%= @recipe.description %></p>
      <h3 class="my-3">Recipe Chef Details</h3>
      <ul>
        <li>Chef Name: <%= @recipe.chef_name %></li>
      </ul>
      <h3 class="my-3">Recipe Tags</h3>
      <ul>
        <% @recipe.tags.each do |tag| %>
          <li><span class="badge badge-secondary"><%= tag.name %></span></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key.to_sym) %>">
  	<%= value %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Marley Spoon</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">About Us</a>
      </li>
    </ul>
  </div>
</nav>